Repository almandite1/shogunate_map_alteration, pull requests merged in 2021-08, with the labels that each got.

#205 English Motto Translation, German Lake and Sea Translation
  localization/english/dynasties/shgnt_dynasty_names_l_english.yml
  localization/english/shgnt_mottos_l_english.yml
  localization/french/dynasties/shgnt_dynasty_names_l_french.yml
  localization/german/dynasties/shgnt_dynasty_names_l_german.yml
  localization/german/map_items_l_german.yml
  localization/korean/dynasties/shgnt_dynasty_names_l_german.yml
  localization/russian/dynasties/shgnt_dynasty_names_l_russian.yml
  localization/spanish/dynasties/shgnt_dynasty_names_l_spanish.yml
Labels: translation

#215 German Motto Translation, Fix of small English Motto translation incontinuities
  localization/english/shgnt_mottos_l_english.yml
  localization/german/00_provinces_l_german.yml
  localization/german/nmih_character_name_l_german.yml
  localization/german/nmih_dynasty_name_l_german.yml
  localization/german/shgnt_mottos_l_german.yml
Labels: bug, translation

#267 Update rivers.png
  map_data/rivers.png
Labels: enhancement
